<?php
require __DIR__ . '/../FizzBuzz.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-07-29 at 11:12:54.
 */
class FizzBuzzTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FizzBuzz
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new FizzBuzz(1,15);
    }

    protected function tearDown()
    {
    }

    /**
     * @covers FizzBuzz::publish
     */
    public function testPublish()
    {
        $expected = <<<EOT
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz

EOT;
        $this->expectOutputString($expected);
        $this->object->publish();
    }

    /**
     * @dataProvider provider
     * @covers FizzBuzz::evaluate
     */
    public function testEvaluate($no, $fizzbuzz)
    {
        $this->assertEquals($fizzbuzz, $this->object->evaluate($no));
    }

    /**
     * dataProvider
     */
    public function provider()
    {
        return [
            [1, '1'],
            [3, 'Fizz'],
            [5, 'Buzz'],
            [15, 'FizzBuzz'],
            [100, 'Buzz'],
        ];
    }
}
